<?php

use Illuminate\Database\Seeder;
use LaNeta\User;

class LaNetaSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		/*User::create(
			[
				'first_name' => 'Mayreny',
				'last_name' => 'Gonzalez',
				'username' => 'E2',
				'email' => 'mayrenyg@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 1,
				'password' => '$2a$10$uUGhu11hSVhfDTzkQEmheu/a0lvY54HEVuXSrrYMTC//rg6KE1hgi',
				'image' => '/uploads/default_user.png',
				'hits' => 0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()	
			],
			[
				'first_name' => 'Daniella',
				'last_name' => 'Moralres',
				'username' => 'E3',
				'email' => 'daniplayola@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 1,
				'password' => '$2a$10$BXZW5meYLvpoZHHFmegXW.gmP3X4MULB/F/5s8Cad2BL1VEgFKjGm',
				'image' => '/uploads/default_user.png',
				'hits' => 0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name' => 'Geomaglys',
				'last_name' => 'Colina',
				'username' => 'geomaglys',
				'email' => 'geomaglysc@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 1,
				'password' => '$2a$10$ZiiW2iU5CRE1UVnGe4XDWO1zeqCPORyEQESHDvunbsuIXhJ6NAQA.',
				'image' => '/uploads/default_user.png',
				'hits' => 0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name' => 'Daimery',
				'last_name' => 'Fruscella',
				'username' => 'B9',
				'email' => 'daymeria3@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 0,
				'password' => '$2a$10$luSNwgxwM0VIVW027KdaFeXGSS5aC4iqTH/KpTs6dPKdkxNTPv1Zi',
				'image' => '/uploads/default_user.png',
				'hits' => 0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name' => 'Marta',
				'last_name' => 'Gonzalez',
				'username' => 'E5',
				'email' => 'monina_albiceleste@hotmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 1,
				'password' => '$2a$10$pNCXLnEZPak/77soJmGmf.T689c.akAAq6wOvydaiYv0/dn8zcKdO',
				'image' => '/uploads/default_user.png',
				'hits' => 0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name' => 'Thady',
				'last_name' => 'carabaño',
				'username' => 'B4',
				'email' => 'thadycristina@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 1,
				'password' => '$2a$10$pisuQGsJxlpoDxYHTdXhAu2XA74UIAGA68qbNHBa7YWLjEEO5Y7OW',
				'image' => '/uploads/default_user.png',
				'hits' => 17,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name' => 'Yessica',
				'last_name' => 'Abreo',
				'username' => 'B6',
				'email' => 'ysykalexandra@gmail.com',
				'gender' => 2,
				'phone' => '+15559990000',
				'location' => 1,
				'status' => 0,
				'password' => '$2a$10$jx4eTqiEkAftBSqJb5eaue31NKDgOvXz.5nxyQL0at6ItZ1JQ9WSa',
				'image' => '/uploads/default_user.png',
				'hits' => 27,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[		
				'first_name'=>'Mercis', 
				'last_name'=>'Martinez',
				'username'=>'B5',
				'email'=>'mercism@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$CBwkAXzygKiZgSjVatcsx.3IyyjfT82iGgUA1PocLh4aWmZgMwr16',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Mireya', 
				'last_name'=>'Reyna',
				'username'=>'E4',
				'email'=>'mreyna93.02@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$M2ua8jQ2ngH82exGrXmcgutkg.qj0y0B19Qg4ukkolo2RnxiT6.Xy',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Marcos', 
				'last_name'=>'Perez',
				'username'=>'E8',
				'email'=>'mapebri@hotmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$u/RKlwQoBFJh3HGgQYC6cOURYHDobl9yArF2Q.VErbMsiuEgdm5ui',
				'image'=>'/uploads/default_user.png',
				'hits'=>11,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Daniela', 
				'last_name'=>'Damiano',
				'username'=>'B8',
				'email'=>'daniano_daniela@hotmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$lYxi2.bmq3u6ttmgRwY02O8B5Xx6PR.bKl7Wx8HvDCAHCkAkYsywS',
				'image'=>'/uploads/default_user.png',
				'hits'=>4,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'José Manuel', 
				'last_name'=>'Egañez',
				'username'=>'E7',
				'email'=>'jmeganez@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$zIf35GaI.g5BXxJB3K86Luf.NZOnVF7h2JaXHO8Bdn/TZmCN2gNP.',
				'image'=>'/uploads/default_user.png',
				'hits'=>14,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Eliana', 
				'last_name'=>'Montezuma',
				'username'=>'E14',
				'email'=>'elisurga@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$z22xFMWgQDDT0z90Ak/Eq.ZxAoGIBbm0Bsc7G.YnzTlhihQDZqb46',
				'image'=>'/uploads/default_user.png',
				'hits'=>71,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Larry', 
				'last_name'=>'MARQUEZ',
				'username'=>'E11',
				'email'=>'proyectotramo1@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$3QZVWwZ2lqHgdC9ISHmYzu.4lLRm2ia00YO5K0AskwmJjFKBHIXd6',
				'image'=>'/uploads/default_user.png',
				'hits'=>53,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'José Manuel', 
				'last_name'=>'Suárez',
				'username'=>'B00',
				'email'=>'gendou_kun@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$3SRh3KpxEHOxJ/Bl0LEZ3O8t8lagFLhRMbD0fP0292mLlmeUBNHxK',
				'image'=>'/uploads/default_user.png',
				'hits'=>1,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Victor', 
				'last_name'=>'Molina',
				'username'=>'E10',
				'email'=>'molinavictor_95@hotmail.es',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$qfI/q2/2rR9PxiVJa4LlyeFmuH2eB1F1oApdnnNf1o..9WtVpt61K',
				'image'=>'/uploads/default_user.png',
				'hits'=>35,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Social', 
				'last_name'=>'Media',
				'username'=>'social_media',
				'email'=>'www.laneta@gmail.com',
				'gender'=>'0',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$keT8/al67c9vWNvkl4SDJOnw3.C8iAEgr/pyzCS/E6Sjx5liL5gPS',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Edwina', 
				'last_name'=>'Quintero',
				'username'=>'E9',
				'email'=>'quinteroedwina@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$gv3eavfwGqRGdBKCPiu/vet0CP0lhgGxjsCeeJTunTUEImv30Gnym',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Cesar', 
				'last_name'=>'Olarte',
				'username'=>'E12',
				'email'=>'cesarolarteq92@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$Uobwv9k3yKdG19cUPmvzS.BECZX70mH0Jo6/0Xo5V5gq2co7J7EOO',
				'image'=>'/uploads/default_user.png',
				'hits'=>26,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Lilys', 
				'last_name'=>'Tinoco',
				'username'=>'B17',
				'email'=>'lelys95tinoco@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$LXUQhJVNcBki4XnDVCAKUe5i.HiLOGBIUpSby/nRITHA.3QcydDe6',
				'image'=>'/uploads/default_user.png',
				'hits'=>12,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Maria', 
				'last_name'=>'gonzalez',
				'username'=>'B19',
				'email'=>'ale.gm@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$SCP/M7kX1gS79.xhEivphe2ltnbVC/5Kd09cKyEdfGxNeztIzVig2',
				'image'=>'/uploads/default_user.png',
				'hits'=>19,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Janeth', 
				'last_name'=>'Torres',
				'username'=>'B20',
				'email'=>'janethtorres406@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$Nu8xs8DFEgwEOGfSRrN3bOKuYn34MmV9U4yvjX8TuPrwfpuhR0WX6',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Yadira', 
				'last_name'=>'Salas',
				'username'=>'B21',
				'email'=>'yadirum@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$UkXV7/GCN598jX0t6aI5wOY3E7/kVQnXe3N56EhtRjzViUCs6RqDa',
				'image'=>'/uploads/default_user.png',
				'hits'=>6,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Ana', 
				'last_name'=>'Nuñez',
				'username'=>'B22',
				'email'=>'anacristin50@hotmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$qC3Il0dFu3hOEBD/62/Yc.jeKf4zXSz90qN3to6mLPDFPc7LBVcQq',
				'image'=>'/uploads/default_user.png',
				'hits'=>4,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Alexis', 
				'last_name'=>'Palacios',
				'username'=>'B23',
				'email'=>'alexispr@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$xI.HMkfYkkwEM85hsn6LMOC40c5NpDdmBrOmXLpEMGq2c2bInYqP2',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Juan', 
				'last_name'=>'Perez',
				'username'=>'B24',
				'email'=>'jperfa@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$2rStpZoNS0s.O3dZImlCqeOZt8f6jYh.cdhSwHgKnKDeWEO/2rI6G',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Jairo', 
				'last_name'=>'Reyes',
				'username'=>'B25',
				'email'=>'jairoreyes20@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$NeHWsy5FK99da7ISHVq5KuMVB58MyhlqPrLG/z5kXMQ60IAPNYBIi',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Arnoldo', 
				'last_name'=>'Arcaya',
				'username'=>'B26',
				'email'=>'arnoldo.jas@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$QYhgYDXqzf3GL1jVcRakrOr/hmycBJH4QrL9VmDjEXdlRZq1kgDqe',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Stefany', 
				'last_name'=>'Izquiel',
				'username'=>'B27',
				'email'=>'stefanyizquiel@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$K6yzpjbJ5Gnnr0HM35x/m.VW3uRRJstnnfPgToJ0PSUMiKY69BgO2',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Maidolis', 
				'last_name'=>'Ramones',
				'username'=>'B28',
				'email'=>'maidolisramones@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$3IS/9bSHQrL8o1piS2TI0OKhFhwyWT35wknrNbJuHSs3DTaRfx3qC',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Ronald', 
				'last_name'=>'Moreno',
				'username'=>'B29',
				'email'=>'rjmoreno1082@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$ORiJHEhFtGoD/j5ZlCS5KeinqTWVq9ij.y3SBU5GD.9ZGKofZPgcC',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Adriana', 
				'last_name'=>'Sulbaran',
				'username'=>'B30',
				'email'=>'adrianasulbaran@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$OR5Acmfxcj0FJf1v1DudYeedjJ9gJ5pAKM9TfgVMkrLO0WHx/tceC',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Alfredo',
				'last_name'=>'Mavarez',
				'username'=>'E31',
				'email'=>'mavarezalfredo@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$.W6mdyKgnPE1wkMB.Klf6.JpIa14tVJ9UFUkFML8/uAZEmt3YsDVa',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Antony', 
				'last_name'=>'Veliz',
				'username'=>'B32',
				'email'=>'antony.veliz12@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'0',
				'password'=>'$2a$10$rtza2S8T4UZ8U/8pvkc16eHWbWG9cp0Cv4DCpiyYBLbcjNJPVlaxO',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Itzari',
				'last_name'=>'Briceño',
				'username'=>'B33',
				'email'=>'itzari.212@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$Srvsok87db5Ivgz5pZw1peMbCTJSXfe1.IQmYZ9SDgM1O915LVupO',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Ricardo', 
				'last_name'=>'Quintero',
				'username'=>'B34',
				'email'=>'ricardodq90@hotmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$hwUcvYScACGPNQ0w2dZAGuzPXXoGFrvktmKdVnmE1ThA5Gb0shRYK',
				'image'=>'/uploads/default_user.png',
				'hits'=>2,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Yaneivy', 
				'last_name'=>'Pizzani',
				'username'=>'B35',
				'email'=>'pizzaniyaneivy@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$TEgtnDYWUmp6H2JBLBEa0esyXeXOekuAjkJxhnEL4PkahywOV.KFa',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Engelberth', 
				'last_name'=>'Centeno',
				'username'=>'B36',
				'email'=>'engel19cfc@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$bfRZGgJJjgRdJncAS4csZucmyT6M20eHFzVO0VI97BAKW3xTOmFGq',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Eduardo', 
				'last_name'=>'Raga',
				'username'=>'B37',
				'email'=>'eduardoraga1@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$nFO4OQcnUGJy5tbr.evwlOFLPj7KyFxdp6t.V7FncmSZcGh5tq5S2',
				'image'=>'/uploads/default_user.png',
				'hits'=>0,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Paola', 
				'last_name'=>'Chirinos',
				'username'=>'B38',
				'email'=>'paola.chirinos700@gmail.com',
				'gender'=>'2',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$Evcf5ibCHqkbIsOK3.vzPuL1ESBsgSBwEXndef.kcdoctEb7CsWb2',
				'image'=>'/uploads/default_user.png',
				'hits'=>5,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			],
			[
				'first_name'=>'Julio', 
				'last_name'=>'aular',
				'username'=>'B39',
				'email'=>'jaular82@gmail.com',
				'gender'=>'1',
				'phone'=>'+15559990000',
				'location'=>'1',
				'status'=>'1',
				'password'=>'$2a$10$b6Tu6tz/.jP93xY6PioI6.WUZzrFYPtJ599POJzIVcbiPTBTvgepa',
				'image'=>'/uploads/default_user.png',
				'hits'=>19,
				'biography' => 'Donec rutrum congue leo eget malesuada. Vivamus suscipit tortor eget felis porttitor volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla porttitor accumsan tincidunt. ',
				'remember_token' => str_random(10),
				'verified' => User::USUARIO_VERIFICADO,
				'verification_token' => User::generarVerificationToken()
			]
		);*/
	}
}
